### ISSUE TITLE
JUST A QUESTION!

### ISSUE THREAD

**Issue by Talhamehar007** [RNR1/DoneWithIt#6]
Is it a fully functional application built with expo??

**Comment by RNR1** [comment]
Hi!
This is a demo app I made as part of the react native course of Mosh Hamedani

**Comment by Talhamehar007** [comment]
As you had enrolled in Mosh Hamdedani's React Native Course, if you could share the video course with me, that would be appreciated!

**Comment by RNR1** [comment]
The course is available here:

https://codewithmosh.com/p/the-ultimate-react-native-course

I highly recommend it!
